# Building Neural NEtwork from Scratch 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('/Users/kishan/Desktop/python/deep_learning/digit-recognizer/train.csv')

In [3]:
data = np.array(df)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
y_dev = data_dev[0]
x_dev = data_dev[1:n]
x_dev = x_dev / 255.

data_train = data[1000:m].T
y_train = data_train[0]
x_train = data_train[1:n]
x_train = x_train / 255.
_,m_train = x_train.shape

In [4]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2
def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [5]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [6]:
W1, b1, W2, b2 = gradient_descent(x_train, y_train, 0.10, 500)

Iteration:  0
[0 1 1 ... 1 1 1] [3 8 2 ... 7 4 2]
0.11858536585365853
Iteration:  10
[0 7 1 ... 7 1 9] [3 8 2 ... 7 4 2]
0.21436585365853658
Iteration:  20
[0 7 1 ... 7 1 6] [3 8 2 ... 7 4 2]
0.29878048780487804
Iteration:  30
[7 7 1 ... 7 1 2] [3 8 2 ... 7 4 2]
0.35080487804878047
Iteration:  40
[7 7 8 ... 7 1 2] [3 8 2 ... 7 4 2]
0.39519512195121953
Iteration:  50
[7 7 8 ... 7 1 2] [3 8 2 ... 7 4 2]
0.4334878048780488
Iteration:  60
[7 7 8 ... 7 1 2] [3 8 2 ... 7 4 2]
0.468609756097561
Iteration:  70
[7 7 8 ... 7 4 2] [3 8 2 ... 7 4 2]
0.5029512195121951
Iteration:  80
[7 7 8 ... 7 4 2] [3 8 2 ... 7 4 2]
0.5389024390243903
Iteration:  90
[7 7 5 ... 7 4 2] [3 8 2 ... 7 4 2]
0.5717073170731707
Iteration:  100
[3 7 5 ... 7 4 2] [3 8 2 ... 7 4 2]
0.6044878048780488
Iteration:  110
[3 7 5 ... 7 9 2] [3 8 2 ... 7 4 2]
0.631
Iteration:  120
[3 7 5 ... 7 9 2] [3 8 2 ... 7 4 2]
0.6553414634146342
Iteration:  130
[3 7 5 ... 7 9 2] [3 8 2 ... 7 4 2]
0.6747317073170732
Iteration:  140
[3 7 5 ...